// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // In Prisma 7 this config is only used by the CLI (migrate, db pull, etc.),
    // which hangs on Supabase's pooled transaction-mode URL. Use the session-mode
    // URL here; the app connects at runtime with DATABASE_URL via @prisma/adapter-pg.
    url: env("DIRECT_URL"),
  },
});
